// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import UserOutlined from '/Users/wuzongwei/Documents/www/nofx-1/admin-web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import TableOutlined from '/Users/wuzongwei/Documents/www/nofx-1/admin-web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TableOutlined';
import SettingOutlined from '/Users/wuzongwei/Documents/www/nofx-1/admin-web/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { UserOutlined, TableOutlined, SettingOutlined };
